/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface fileInfoInterface {
  TOTAL_CHUNK: number;
  createTime: number;
  fileName: string;
  fileSize: number;
  fileType: string;
}
